### ISSUE TITLE
How can I use a another csredis not Nuget one?

### ISSUE THREAD

**Issue by jeong760** [bonesoul/CoiniumServ#793]
Dears,

I want to change a csredis that my own compiled version but when I replacement it and running a CoiniumServ it shows me following error related with csredis.

So how can I use my own compiled csredis?

05/09/2017 03:52:04 +09:00 [Error] [Pool] [Bitcoin] Pool initilization failed; Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Persistance.Providers.IStorageProvider ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Persistance.Providers.Redis.RedisProvider ---> System.IO.FileLoadException: Could not load file or assembly 'csredis, Version=3.2.1.0, Culture=neutral, PublicKeyToken=1afd0264bbe4a44a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at CoiniumServ.Persistance.Providers.Redis.RedisProvider.Initialize()
   at lambda_method(Closure , Object[] )
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.Resolve[ResolveType](String name, NamedParameterOverloads parameters)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CoiniumServ.Pools.Pool.InitStorage() in D:\git_repos\coinsrc\src\CoiniumServ\Pools\Pool.cs:line 207
   at CoiniumServ.Pools.Pool.Initialize() in D:\git_repos\coinsrc\src\CoiniumServ\Pools\Pool.cs:line 156

Regards,
John Ahn

**Comment by vagabondan** [comment]
Something like that:
https://github.com/bonesoul/CoiniumServ/issues/826#issuecomment-316332378
