### ISSUE TITLE
[Error] [HybridStorage] An exception occured while comitting share:

### ISSUE THREAD

**Issue by owner232** [bonesoul/CoiniumServ#837]
What needs to be done to fix this error?

redStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.
04:47:22 [Error] [HybridStorage] [USDE] An exception occured while comitting share: Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.
04:47:23 [Error] [HybridStorage] [USDE] An exception occured while comitting share: Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.

**Comment by owner232** [comment]
Thanks for the fork, It is working excellent for me. In case anyone needs it here is the compiled windows version. It compiled to bin/release. You are more than welcome to post virus scans.
https://ufile.io/1e28s
I am getting the error [Error] [CoiniumServ.Markets.MarketManager] [global] Sequence contains no elements. I believe this is because the market config is not set right anyone know how this is set up?

**Comment by mario1987** [comment]
@owner232  Does that complicated version also do payouts correctly ?

**Comment by owner232** [comment]
Yes it works absolutely perfect

**Comment by mario1987** [comment]
@owner232  Ok tnx.  but I have a problem with the pool I don't know if it is due to the configuration but I am not able to find blocks. I used to find blocks with the standard coiniumServ.

I am mining X11 any idea on how to solve it tnx again.

**Comment by owner232** [comment]
These are the settings i run on usde coin
},
    "job": {
        "blockRefreshInterval": 2,
        "rebroadcastTimeout": 40
    },
    "stratum": {
        "enabled": true,
        "bind": "0.0.0.0",
        "diff": 32,
        "vardiff": {
            "enabled": true,
            "minDiff": 0.01,
            "maxDiff": 640000,
            "targetTime": 15,
            "retargetTime": 60,
            "variancePercent": 30
        }

**Comment by owner232** [comment]
Also make sure you have at least 8 connections on the wallet

**Comment by mario1987** [comment]
Tnx i will try it out.

**Comment by mario1987** [comment]
@owner232  That version is not working for me I am using it now for at least 8 hours  and have 17 connections. I tried the standard coiniumServ before with that i  am finding blocks but unable to do payouts ps both have the same coin configuration.  

In the standard coiniumServ it always says we thought a block was found but deamon rejected it.  but this version does not say that at all.  maybe the deamon does not get the hashes  I don't know.

**Comment by vagabondan** [comment]
@owner232 "blockRefreshInterval": 2, - means that you are requesting your wallet software for getblocktemplate each 2 milliseconds i.e. 500 times per second... It will curse you someday for that:)
It makes sense to keep blockRefreshInterval value near 1000

**Comment by mario1987** [comment]
Ok I will try that.  The standard version of coiniumServ  finds blocks even with the blockRefreshInterval": 2 in config of coin.

**Comment by vagabondan** [comment]
This version of CS has bug block polling. In fact it's not working at all.
Fix is here:
https://github.com/vagabondan/CoiniumServ/commit/034da4cd09723836dacb238a5140900cb8d079fa

**Comment by mario1987** [comment]
@vagabondan  I am using the version of yours https://github.com/vagabondan/CoiniumServ  for some time now  and i am not able to find blocks. but with the standard version i am finding blocks.

**Comment by owner232** [comment]
Haha ill be sure to change that, Thanks for the info
I am not experiencing the same issue as you guys, The wallet im using is 3 years old as this coin has not been updated yet. I tried running the new server but got a ton of errors on the rpc connection. I am going to keep on using the older version.
Here is the compiled  new server version that vaga just posted. https://ufile.io/2clx4

**Comment by vagabondan** [comment]
@mario1987 well, if you explain details maybe we can figure out the reason, because at least for LTC version with my modifications is working well for me.

**Comment by mario1987** [comment]
@vagabondan I will explain it it is simple I am not finding any blocks with this version  I am mining XRBC, it is x11 algo with a difficulty between 8 to 16 on net you can visit the pool here [http://84.26.17.231/](url).
But when I am mining it on the standard CS I find blocks but payments does not work.  If you want we can have a chat on Teamvieuwer.

**Comment by mario1987** [comment]
@vagabondan  Or maybe you can try to run this coin in a pool
https://bitcointalk.org/index.php?topic=1737799.msg21081619#msg21081619
Maybe you will get the same issues as me if you don't have a miner for it I will direct my miner to the pool.
maybe the version only works for LTC.

**Comment by mario1987** [comment]
I am getting this in the debug log of the wallet 

accepted connection 76.114.105.34:56302
send version message: version 60013, blocks=647033, us=212.168.1.127:4528, them=76.114.105.34:56302, peer=76.114.105.34:56302
Added time data, samples 8, offset +0 (+0 minutes)
receive version message: version 60013, blocks=647033, us=84.26.17.231:4528, them=76.114.105.34:4528, peer=76.114.105.34:56302
trying connection 172.23.119.251:4528 lastseen=389840.9hrs
connection timeout
trying connection 92.80.97.24:4528 lastseen=181.6hrs
ThreadRPCServer method=validateaddress
ThreadRPCServer method=validateaddress

**Comment by vagabondan** [comment]
@mario1987 As I understood well the latter is the wallet log with standard CS version (because of ProcessBlock: ACCEPTED phrase).
Do you have logs (CS (debug and packet at verbosity level) and wallets) with my CS version?

**Comment by mario1987** [comment]
@vagabondan  No it is the wallet log with your version 


[CS-packet-20170823.TXT](https://github.com/bonesoul/CoiniumServ/files/1243569/CS-packet-20170823.TXT)

[CS-server.TXT](https://github.com/bonesoul/CoiniumServ/files/1243570/CS-server.TXT)

[CS-debug.TXT](https://github.com/bonesoul/CoiniumServ/files/1243571/CS-debug.TXT)
[Wallet-debug.TXT](https://github.com/bonesoul/CoiniumServ/files/1243572/Wallet-debug.TXT)

**Comment by vagabondan** [comment]
@mario1987 Thank you! Something is definetly wrong with Proof Of Work function:
POW: 6b33f25bf896d6b102ae236f6c055e63f33b3e24f3320e74b8def9640681880ef1e4a3b75b677aa75770d2e9c23157dcd463ef35bed26db6b9d538161fc0a48d
TGT:         128e8400000000000000000000000000000000000000000000000000

By the way, what module is this?
Metrics.PerfCounters.PerformanceCounters

**Comment by owner232** [comment]
Strangely after running the pool for weeks perfectly fine after compiling and attempting to run that new client i am now getting an error on the orginal server 01:20:39 [Error] [CoiniumServ.Server.Mining.Stratum.StratumServer] [USDE] Send
System.Net.Sockets.SocketException (0x80004005): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.Send(Connection connection, Byte[] buffer, Int32 start, Int32 count, SocketFlags flags) in C:\pool\src\CoiniumServ\Server\Mining\Stratum\Sockets\SocketServer.cs:line 254

I changed the port to 3334 and for some reason im getting paid from mining but the pool is not seeing any blocks and doesnt know the server mined any.

**Comment by vagabondan** [comment]
@owner232 What is on line 254 of C:\pool\src\CoiniumServ\Server\Mining\Stratum\Sockets\SocketServer.cs file in your CS version? 
Mine is different apparently from yours...

**Comment by owner232** [comment]
Here is 238 to 278

public virtual int Send(Connection connection, byte[] buffer, int start, int count, SocketFlags flags)
        {
            if (connection == null) 
                throw new ArgumentNullException("connection");

            if (buffer == null) 
                throw new ArgumentNullException("buffer");

            if (!connection.IsConnected)
                return 0;

            var totalBytesSent = 0;
            var bytesRemaining = buffer.Length;

            try
            {
                while (bytesRemaining > 0) // Ensure we send every byte.
                {
                    int bytesSent = connection.Socket.Send(buffer, start, count, flags);                       

                    if (bytesSent > 0)
                        OnDataSent(new ConnectionDataEventArgs(connection, buffer.Enumerate(totalBytesSent, bytesSent))); // Raise the Data Sent event.

                    // Decrement bytes remaining and increment bytes sent.
                    bytesRemaining -= bytesSent;
                    totalBytesSent += bytesSent;
                }
            }
            catch (SocketException socketException)
            {
                RemoveConnection(connection); // An error occured while sending, connection has disconnected.
                _logger.Error(socketException, "Send");
            }
            catch (Exception e)
            {
                RemoveConnection(connection); // An error occured while sending, it is possible that the connection has a problem.
                _logger.Error(e, "Send");
            }

            return totalBytesSent;
        }

**Comment by owner232** [comment]
I didnt touch this build i just changed the name of the directory and ran the new one you posted it gave errors so i just reverted and this server has not worked since, its strange i even restarted the server changed all the databases the only thing that made it not display that error is to change the stratum port from 3333 to 3334

**Comment by owner232** [comment]
08/22/2017 23:24:40 -05:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [USDE] Stratum client connected: "146.185.151.11:28970"
08/22/2017 23:24:40 -05:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [USDE] Stratum client connected: "146.185.151.11:28968"
08/22/2017 23:24:41 -05:00 [Debug] [CoiniumServ.Mining.MinerManager] [USDE] Authenticated miner: GYZST6SQjrsduxnooe7CuGEC7roDa14BLS [146.185.151.11:28970]
08/22/2017 23:24:41 -05:00 [Debug] [CoiniumServ.Mining.MinerManager] [USDE] Authenticated miner: GYZST6SQjrsduxnooe7CuGEC7roDa14BLS [146.185.151.11:28968]
08/22/2017 23:24:42 -05:00 [Debug] [CoiniumServ.Shares.ShareManager] [USDE] Share accepted at 45.17/32 by miner GYZST6SQjrsduxnooe7CuGEC7roDa14BLS
08/22/2017 23:24:43 -05:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [USDE] Stratum client connected: "104.131.104.33:57294"
08/22/2017 23:24:44 -05:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [USDE] Stratum client disconnected: "104.131.104.33:57294"
08/22/2017 23:24:44 -05:00 [Debug] [CoiniumServ.Server.Mining.Stratum.StratumServer] [USDE] Stratum client disconnected: "104.131.104.33:57294"
08/22/2017 23:24:44 -05:00 [Error] [CoiniumServ.Server.Mining.Stratum.StratumServer] [USDE] Send
System.Net.Sockets.SocketException (0x80004005): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.Send(Connection connection, Byte[] buffer, Int32 start, Int32 count, SocketFlags flags) in C:\pool\src\CoiniumServ\Server\Mining\Stratum\Sockets\SocketServer.cs:line 254



Hmm the 104 ip is a big mining rig

**Comment by vagabondan** [comment]
@owner232 The source does not correlate with binary you are running:
line 254 is 
```
{
            while (bytesRemaining > 0) // Ensure we send every byte.
```
You may need check your environment carefully.

**Comment by owner232** [comment]
This is the source that is running i recompiled the original and everything

**Comment by mario1987** [comment]
@vagabondan  What do you mean by "what module is this? Metrics.PerfCounters.PerformanceCounters"  ?

**Comment by vagabondan** [comment]
@mario1987 CS-debug.TXT reads:

```
08/23/2017 00:16:00 +02:00 [Debug] [Metrics.PerfCounters.PerformanceCounters] [global] Registering performance counter [Free System Page Table Entries] in category [Memory] for instance [none]
08/23/2017 00:16:00 +02:00 [Debug] [Metrics.PerfCounters.PerformanceCounters] [global] Registering performance counter [Pages Input/sec] in category [Memory] for instance [none]
08/23/2017 00:16:00 +02:00 [Debug] [Metrics.PerfCounters.PerformanceCounters] [global] Registering performance counter [Pages/sec] in category [Memory] for instance [none]
08/23/2017 00:16:00 +02:00 [Debug] [Metrics.PerfCounters.PerformanceCounters] [global] Registering performance counter [Pool Nonpaged Bytes] in category [Memory] for instance [none]
08/23/2017 00:16:00 +02:00 [Debug] [Metrics.PerfCounters.PerformanceCounters] [global] Registering performance counter [Pool Paged Bytes] in category [Memory] for instance [none]
```

Metrics.PerfCounters.PerformanceCounters - is something external to CS.

**Comment by mario1987** [comment]
@vagabondan  It comes from the OS 

Performance counters in Windows and Linux provide insight into the performance of hardware components, operating systems, and applications. Log Analytics can collect performance counters at frequent intervals for Near Real Time (NRT) analysis in addition to aggregating performance data for longer term analysis and reporting.

I don't know why it is there  I am running server 2016.

**Comment by vagabondan** [comment]
@mario1987 what about config/coins/reddbytecoin.json config?

**Comment by mario1987** [comment]
@vagabondan  what about it ?

**Comment by mario1987** [comment]
@vagabondan  I am no mining the the standard cs and found 3 blocks already. but it is not registering on the cs that it has found blocks.  and with your version I am not finding any blocks so I can't check that payments works.

**Comment by mario1987** [comment]
@vagabondan  I have found the Metrics.PerfCounters.PerformanceCounters  it is installed in visual studio 2017.  But I did not mark it to be compiled with cs.  So I don't know why it is in the logs of cs.

**Comment by mario1987** [comment]
@vagabondan  by the way in  CoiniumServ/src/CoiniumServ/packages.config you can see that Metrics are installed with cs. I just found that.

**Comment by mario1987** [comment]
@vagabondan  As I am thinking now the coin that I am mining does not use SIGWIT as LTC does maybe that is the problem. The logs that I am going to upload now is from the standard cs

Coin Wallet with found block
[CoinWallet-debug.TXT](https://github.com/bonesoul/CoiniumServ/files/1245668/CoinWallet-debug.TXT)

CS Logs of standard CoiniumServ not recognizing and displaying the found block
[Standard-CS-debug.TXT](https://github.com/bonesoul/CoiniumServ/files/1245671/Standard-CS-debug.TXT)
[Standard-CS-packet-20170823.TXT](https://github.com/bonesoul/CoiniumServ/files/1245672/Standard-CS-packet-20170823.TXT)
[Standard-CS-server.TXT](https://github.com/bonesoul/CoiniumServ/files/1245673/Standard-CS-server.TXT)

**Comment by vagabondan** [comment]
@mario1987 as I wrote earlier https://github.com/bonesoul/CoiniumServ/issues/837#issuecomment-324231909 the is with your proof-of-work function: it produces too large hash, twice larger than it should be. So, I asked you show me your config/coins/reddbytecoin.json because it is absent in this repository.
