### ISSUE TITLE
[Help] DASH - Miner: System.Net.ProtocolViolationException

### ISSUE THREAD

**Issue by nghieppv** [bonesoul/CoiniumServ#852]
I mining DASH, when runing in debug.log have some error log from WebServer, I don't know where this error come from. Help me. @@

Unhandled web-server exception: System.Net.ProtocolViolationException

```
10/12/2017 02:12:17 +00:00 [Error] [WebServer] [global] Unhandled web-server exception: System.Net.ProtocolViolationException: Bytes to be written to the stream exceed the Content-Length bytes size specified.
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass27.<RenderView>b__26(Stream stream)
   at Nancy.Hosting.Self.NancyHost.OutputWithDefaultTransferEncoding(Response nancyResponse, HttpListenerResponse response)
   at Nancy.Hosting.Self.NancyHost.ConvertNancyResponseToResponse(Response nancyResponse, HttpListenerResponse response)
   at Nancy.Hosting.Self.NancyHost.Process(HttpListenerContext ctx)
```

Please, help me !! ^^

**Comment by bonesoul** [comment]
Need more details on this (the exact web request at least). Closing it until an update.
