### ISSUE TITLE
Blocks being accepted in wallet but not in CoiniumServ, can't pay miners

### ISSUE THREAD

**Issue by CMvet** [bonesoul/CoiniumServ#913]
So I have everything setup and running on a windows machine using mysql and Redis 3.0.504 and I'm solo mining with my Antminer on a Scrypt PoW/PoS coin.  Everything connects fine with no errors given however I find blocks (noted on my antminer and on the wallet) but the CoiniumServe only ever shows;

01/16/2018 16:42:55 -08:00 [Debug] [ShareManager] [Pokercoin] Share accepted at 6757076.13/125217.4 by miner PJXsMgWia7twT4pgDtwaWHack1zsBdkFvz
01/16/2018 16:42:55 -08:00 [Debug] [ShareManager] [Pokercoin] We thought a block was found but it was rejected by the coin daemon; [460450ee8cffd95bcd728353c3b1bc4ba9890855fab0e40001298cceb8ba5fbf] - reason; Block not found
01/16/2018 16:42:55 -08:00 [Debug] [VardiffManager] [Pokercoin] Difficulty updated to 88736.73 for miner: PJXsMgWia7twT4pgDtwaWHack1zsBdkFvz
01/16/2018 16:42:56 -08:00 [Information] [BlockProcessor] [Pokercoin] No pending blocks found
01/16/2018 16:42:56 -08:00 [Information] [BlockAccounter] [Pokercoin] No pending blocks waiting to get accounted found
01/16/2018 16:42:56 -08:00 [Information] [PaymentProcessor] [Pokercoin] No pending payments found

They are confirmed in the wallet (so have to be accepted by the daemon) and I can spend those coins from the wallet.  Is there something odd here, why is it not connecting properly to the daemon?

I cant set it up to be able to have multiple people mining as it will never pay them.  Any help is greatly appreciated.

edit;  The only error I see in the debug file is;

01/16/2018 22:17:45 -08:00 [Debug] [StatisticsManager] [global] Recached statistics - took 0.043 seconds
01/16/2018 22:17:51 -08:00 [Error] [StratumServer] [Pokercoin] SocketException on ReceiveCallback
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at CoiniumServ.Server.Mining.Stratum.Sockets.SocketServer.ReceiveCallback(IAsyncResult result)
01/16/2018 22:17:51 -08:00 [Debug] [StratumServer] [Pokercoin] Stratum client disconnected: "192.168.2.1:34948"

**Comment by adambant** [comment]
I too have this same problem with an alt coin. When the block mining rate is slow (1 block every few minutes) this usually doesn't happen. But when the block rate gets faster, 10-15 seconds between blocks, CoiniumServ can't keep up, and starts reported lots of failed blocks when in fact they are good blocks. I have about 3 times more blocks showing up on the coin block explorer than CoiniumServ thinks I have. 

Also CoiniumServ starts to get LOTS of timeouts to the daemon. I have a cron job restarting CoiniumServer every 30 minutes which helps reduce the timeouts and errors, but it still has problems keeping up.
