### ISSUE TITLE
Getting this error for bitcoin.

### ISSUE THREAD

**Issue by dracolumina** [bonesoul/CoiniumServ#940]
Getting this error for bitcoin.  Windows server 6 core 16 gigs of ram, fully updated.  15.1 core.

02/04/2018 16:08:32 -08:00 [Error] [Pool] [Bitcoin] Pool initilization failed; Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Pools.INetworkInfo ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Pools.NetworkInfo ---> System.Exception: There was a problem deserializing the response from the coin wallet. ---> Newtonsoft.Json.JsonSerializationException: Error converting value 2.43858497655835E+19 to type 'System.UInt64'. Path 'result.networkhashps', line 1, position 157. ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Double.System.IConvertible.ToUInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at CoiniumServ.Daemon.DaemonBase.GetRpcResponse[T](HttpWebRequest httpWebRequest)
   --- End of inner exception stack trace ---
   at CoiniumServ.Daemon.DaemonBase.GetRpcResponse[T](HttpWebRequest httpWebRequest)
   at CoiniumServ.Daemon.DaemonBase.MakeRpcRequest[T](DaemonRequest walletRequest)
   at CoiniumServ.Daemon.DaemonBase.MakeRequest[T](String method, Object[] parameters)
   at CoiniumServ.Daemon.DaemonClient.GetMiningInfo()
   at CoiniumServ.Pools.NetworkInfo.Recache()
   at CoiniumServ.Pools.NetworkInfo..ctor(IDaemonClient daemonClient, IHashAlgorithm hashAlgorithm, IPoolConfig poolConfig)
   at lambda_method(Closure , Object[] )
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.Resolve(Type resolveType, NamedParameterOverloads parameters)
   at Nancy.TinyIoc.TinyIoCContainer.Resolve[ResolveType](NamedParameterOverloads parameters)
   at CoiniumServ.Container.ObjectFactory.GetNetworkInfo(IDaemonClient daemonClient, IHashAlgorithm hashAlgorithm, IPoolConfig poolConfig)
   at CoiniumServ.Pools.Pool.InitStatisticsServices()
   at CoiniumServ.Pools.Pool.Initialize()

**Comment by dracolumina** [comment]
I have tried everything I can think of searching the web and everything.  Also, how do you make it so that it will run multiple pools? can't seem to figure that one out.

**Comment by jeong760** [comment]
@dracolumina, It caused by Bitcoin NetworkHash info value bigger than Uint64 allowed value. However I’ve alreday solved this please see a [#933](https://github.com/bonesoul/CoiniumServ/issues/933)
